config/routes.rb
Rails.application.routes.draw do
  resources :documents
  root 'documents#searchs'
  get '/search' => 'documents#searchs', as: :search

end

app/models/document.rb
class Document < ActiveRecord::Base
  # We're mounting the uploader the document_attachment attribute.
  # This attribute will store the path to the attachment.
  mount_uploader :document_attachment, DocumentAttachmentUploader
  
  # Setting up ElasticSearch integration
  include Tire::Model::Search
  include Tire::Model::Callbacks
  
  mapping _source: { excludes: ['attachment'] } do
    indexes :id, type: 'integer'
    indexes :title
    indexes :attachment, type: 'attachment'




  end

  def attachment
    # path_to_attachment = document_attachment.file.file
    # open(path_to_attachment) { |file| file.read }
     Base64.encode64 open(document_attachment.path).read
  end

  def to_indexed_json
    to_json(methods: [:attachment])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  def create
    @document = Document.new(document_params)
    @document.save
    redirect_to search_path
  end


  def show
    @document = Document.find(params[:id])
  end

  def new
    @document = Document.new
  end

  def searchs
    if params[:q].nil?
      @documents = []
    else
      @documents = Document.search params[:q]
    end
    # byebug


  end

  private
    def document_params
       params.require(:document).permit :title, :document_attachment
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/new.html.erb
<h1>New Article</h1>  

<%= form_for :document, url: documents_path, multiple: true do |f| %>

  <% if not @document.nil? and @document.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@document.errors.count, "error") %> prohibited
      this document from being saved:</h2>
    <ul>
    <% @document.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>



  <p>
    <%= f.label :document_attachment %><br>
    <%= f.file_field :document_attachment %>    
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to '<- Back', documents_path %>

app/views/documents/searchs.html.erb
<h1>Articles Search</h1>

<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>

<ul>
    <% @documents.each do |document| %>
    <li>
      <h3>
        <%= link_to document.title, document_path(document.id)%>
      </h3>
    </li>
  <% end %>
</ul>

app/views/documents/show.html.erb
<p>
  <%= @document.title %>
  <br>
  <%= @document.attachment%>

</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Elasticsearch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>